version: '3.1'
services:
  app:
    container_name: tenpoApp
    image: nbarrena/tenpo
    build: ./
    links:
      - redis-server
    ports:
      - "8080:8080"
    depends_on:
      - psdb
  psdb:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tenpo
  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
